### ISSUE TITLE
iichid for 13-CURRENT?

### ISSUE THREAD

**Issue by probonopd** [wulf7/iichid#50]
iichid is in packages for 12.1-RELEASE but not (yet?) in 13-CURRENT. Is this planned? We might want to include it in [helloSystem](hellosystem.github.io/docs) Live ISOs.

**Comment by wulf7** [comment]
No this is not planned. There is a plan to commit it in to the base. See https://reviews.freebsd.org/D27777

**Comment by probonopd** [comment]
Thank you very much @wulf7.
