### ISSUE TITLE
hkbd continuously presses enter in panic debugger instead of reading input

### ISSUE THREAD

**Issue by valpackett** [wulf7/iichid#58]
With hkbd as my only keyboard, dropping to kdb (e.g. via `debug.kdb.panic`) results in what seems like continuous Return presses (new copies of the `db>` prompt keep appearing over and over, pushing the panic text away) and the actual keyboard input is not processed. (Using the base version with multireport patches applied, but I think this was happening long before the patches)

**Comment by wulf7** [comment]
I found a typo preventing hkbd to work. Could you test after updating base to e68d76c054d2?

**Comment by valpackett** [comment]
That did it, thanks!
